Feature/add uploader router
ONSdigital/dp-upload-service pull request #11
Opened 2020-09-17 09:08 UTC by sandypadmanabhan

### What
Added uploader to service
Added endpoints to router and upload.go along with the tests 
Added test for initialise.go and deleted mock package

### How to review

Check tests are working 

### Who can review

Describe who worked on the changes, so that other people can review.

2020-09-17 09:26 UTC, daiLlew reviewed
LGTM but I would suggest a 2nd set of eyes from someone who knows more about the task.

2020-09-28 13:11 UTC, gedge requested changes
submitting my review of the first half, so that you can start addressing these issues while I continue reviewing the rest

2020-09-28 13:11 UTC, gedge commented on service/initialise_test.go
> +		server := svcList.GetHTTPServer(cfg.BindAddr, r)
There's only part of the "given... when... then..." structure/pattern here, that I would expect to see a nested "When" like:
```suggestion
       Convey("When GetHTTPServer is called",...
		server := svcList.GetHTTPServer(cfg.BindAddr, r)
```

2020-09-28 13:11 UTC, gedge commented on service/initialise_test.go
> +		So(len(newServiceMock.DoGetHTTPServerCalls()), ShouldEqual, 1)
continuation of previous comment
```suggestion
    Convey("Then the call has reached the right parts of the mock",...
		So(len(newServiceMock.DoGetHTTPServerCalls()), ShouldEqual, 1)
```

2020-09-28 13:11 UTC, gedge commented on service/initialise_test.go
> +		So(len(newServiceMock.DoGetHTTPServerCalls()), ShouldEqual, 1)
would like to see this pattern repeated for each test (sorry!)

2020-09-28 13:11 UTC, gedge commented on README.md
> +    ChunkNumber      int    `schema:"resumableChunkNumber"`
rather than have this list in two places, consider putting a link here to the struct, instead
```suggestion
    [Resumable struct](upload/upload.go)
```

2020-09-29 15:49 UTC, gedge requested changes
still not complete, so here's part 2 of 3 (hopefully)

2020-10-04 12:33 UTC, gedge requested changes
marvellous, just one last comment

2020-10-05 13:27 UTC, gedge approved these changes
thanks for your patience!

2020-10-05 16:43 UTC, merged